eingengraou/2022 08 25 zap on raspberry pi
zaproxy/zaproxy-website pull request #1222
Opened 2022-08-23 19:03 UTC by eingengraou

Signed-off-by:eingengraou
miracleoct21@gmail.com

**- Summary**

**- Test plan**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

2022-08-23 19:09 UTC, kingthorin requested changes
Maybe also give "site/content/blog/2022-08-25-zap-on-raspberry-pi/images/images (7).jpeg" a better name? (The other screenshots seem well named.)

The blank lines in the markdown could definitely be reduced.

I'll do a more complete review later.

2022-08-23 19:09 UTC, kingthorin commented
To address the DCO requirement you'll need to sign-off the commit(s):

- https://github.com/zaproxy/zaproxy/blob/main/CONTRIBUTING.md#developer-certificate-of-origin
- https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff

2022-08-23 19:39 UTC, thc202 commented on site/content/blog/2022-08-25-zap-on-raspberry-pi/index.md
> +- gsoc
Remove this one.

2022-08-24 07:36 UTC, psiinon commented on site/content/blog/2022-08-25-zap-on-raspberry-pi/index.md
> +    - eingengraou
You also need to update [authors.yml](https://github.com/zaproxy/zaproxy-website/blob/master/site/data/authors.yml) and optionally include a picture of yourself or an image you'd like to use for yourself.

2022-08-24 07:39 UTC, psiinon commented on site/content/blog/2022-08-25-zap-on-raspberry-pi/index.md
> + Disclaimer: There's currently no method to run [zap](https://github.com/zaproxy/zaproxy) on an android device alone.
"ZAP" should always be capitalized, unless it is part of a filename such as `zap.sh`

2022-08-25 09:20 UTC, psiinon requested changes
Just minor typos and comments

2022-08-25 09:20 UTC, psiinon commented on site/content/blog/2022-08-25-zap-on-raspberry-pi/index.md
> +The reason for using the core version of ZAP is because it doesn't  contain unneccesary componets like the in-built browser that doesn't  work on the set up.
typo: "components"

2022-08-25 09:20 UTC, psiinon commented on site/content/blog/2022-08-25-zap-on-raspberry-pi/index.md
> +Go to [ZAP official download page](https://www.zaproxy.org/download/) and download the ***`core cross platform package`*** zip file.
As its the same site we can replace `https://www.zaproxy.org/download/` with `/download/`

2022-08-25 09:20 UTC, psiinon commented on site/content/blog/2022-08-25-zap-on-raspberry-pi/index.md
> +```
We usually use put "bash" after the 3 backquotes - that then uses white on black as per https://www.zaproxy.org/faq/how-can-you-import-post-requests/#proxy-another-tool - but its up to you. Either change none or all 😉

2022-08-25 12:37 UTC, thc202 commented on site/content/blog/2022-08-25-zap-on-raspberry-pi/index.md
> +The ***'WRITE'*** button at this point would change colour depicting that you're ready to write into your SD card , but before we write into the storage device click the 'SETTINGS' icon below the gea
`preferences`

2022-08-25 12:37 UTC, thc202 commented on site/content/blog/2022-08-25-zap-on-raspberry-pi/index.md
> +Install any VNC client software from the Google Playstore and launch the application add new host using ***your raspberry pi ip:1*** as Host address, use the user that created the vnc server on your
`Play store`

2022-08-25 12:53 UTC, kingthorin commented on site/content/blog/2022-08-25-zap-on-raspberry-pi/index.md
> +The ***'WRITE'*** button at this point would change colour depicting that you're ready to write into your SD card , but before we write into the storage device click the 'SETTINGS' icon below the gea
Good catch

2022-08-25 13:13 UTC, thc202 commented on site/content/blog/2022-08-25-zap-on-raspberry-pi/index.md
> +All you have to do now is install any browser of your choice, install ZAP's CA certificate and [set up the proxy](https://www.zaproxy.org/docs/desktop/start/proxies/) on the browser and you're good t
This link needs to be changed.

2022-08-25 13:29 UTC, psiinon approved these changes

2022-08-25 13:38 UTC, psiinon commented
Doh, no, just me being stupid :P

2022-08-25 13:40 UTC, thc202 approved these changes

2022-08-25 13:40 UTC, thc202 commented
Thank you!

2022-08-25 13:44 UTC, kingthorin approved these changes
Yup looks good to me.

2022-08-25 13:44 UTC, merged