map local addon initial description
zaproxy/zaproxy-website pull request #2188
Opened 2023-10-12 14:08 UTC by Keindel

please take a look whether the description is good enough

2023-10-12 14:12 UTC, kingthorin reviewed
Maybe add a bit about your motivation to create the add-on? Maybe outline some of your use cases?

2023-10-12 14:12 UTC, kingthorin commented on site/content/blog/2023-10-12-maplocal-add-on/index.md
> +1. RMB on Site or in History Tab to call context menu.
RMB?

2023-10-12 14:12 UTC, kingthorin commented on site/content/blog/2023-10-12-maplocal-add-on/index.md
> +   from here on all requests to the matching url's will return responses with the content of chosen local file
URLs

2023-10-12 14:12 UTC, kingthorin commented on site/content/blog/2023-10-12-maplocal-add-on/index.md
> +   from here on all requests to the matching url's will return responses with the content of chosen local file
Maybe include a screen shot.

A small video or animated gif of an example in action (before/after of a site)

2023-10-12 14:12 UTC, kingthorin commented
To address the DCO requirement you'll need to sign-off the commit(s):

- https://github.com/zaproxy/zaproxy/blob/main/CONTRIBUTING.md#developer-certificate-of-origin
- https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff

2023-10-12 14:15 UTC, psiinon requested changes

2023-10-12 14:15 UTC, psiinon commented on site/content/blog/2023-10-12-maplocal-add-on/index.md
> +date: "2023-10-12"
We're publishing a blog post about 2.14.0 today, so it might be worth holding off for a couple of days 😉

2023-10-12 14:15 UTC, psiinon commented on site/content/blog/2023-10-12-maplocal-add-on/index.md
> +This extension allows you to specify mappings of local resources to replace responses when using ZAP.
Go into a bit more detail for why someone might want to use it?
Esp someone who has not used the same feature in Charles or Proxyman before.

2023-10-12 14:15 UTC, psiinon commented on site/content/blog/2023-10-12-maplocal-add-on/index.md
> +
A screenshot of the dialog would help here

2023-10-12 14:15 UTC, psiinon commented on site/content/blog/2023-10-12-maplocal-add-on/index.md
> +    - Keindel (Andrey Maksimov)
Add your name to https://github.com/zaproxy/zaproxy-website/blob/main/site/data/authors.yml and reference that

2023-10-30 12:38 UTC, Keindel commented
changes applied, expanations and images added

2023-10-30 16:39 UTC, psiinon commented
Looking good, notwithstanding the minor comments already mentioned 😁

2023-10-31 12:21 UTC, psiinon commented
The date needs to change to today - in the folder name as well..

2023-10-31 12:26 UTC, thc202 commented on site/content/blog/2023-10-31-maplocal-add-on/index.md
> +#- https://www.zaproxy.org/blog/2023-10-30-maplocal-add-on/images/image.png
Remove?

2023-10-31 12:39 UTC, psiinon approved these changes

2023-10-31 12:42 UTC, kingthorin approved these changes

2023-10-31 12:52 UTC, merged

2023-10-31 12:52 UTC, thc202 commented
Thank you!