blog: Add post on detachable tabs
zaproxy/zaproxy-website pull request #2805
Opened 2024-09-17 20:07 UTC by ricekot

2024-09-17 20:25 UTC, kingthorin approved these changes

2024-09-17 22:01 UTC, thc202 commented on site/content/blog/2024-09-18-detachable-tabs/index.md
> +Try out this change by [downloading the latest ZAP weekly](https://www.zaproxy.org/download/#weekly) and let us know what you think on the [ZAP User Group](https://groups.google.com/group/zaproxy-use
`/download/#weekly`

2024-09-18 06:20 UTC, thc202 approved these changes

2024-09-18 06:20 UTC, thc202 commented
Thank you!

2024-09-18 07:52 UTC, psiinon commented
Will explain why WIP on Slack in a bit 😁

2024-09-19 08:22 UTC, psiinon requested changes

2024-09-19 08:22 UTC, psiinon commented on site/content/blog/2024-09-18-detachable-tabs/index.md
> +title: "ZAP now has Detachable Tabs!"
Ah, but it doesnt 😁 
ZAP as far as 99% of our users are concerned is the latest released version, which does not support detachable tabs.
If we're going to publish this blog before 2.16 then we have to make it very clear that its only dev/nightly/weekly that support this

2024-09-19 08:22 UTC, psiinon commented on site/content/blog/2024-09-18-detachable-tabs/index.md
> +![An image containing screenshots of two ZAP windows. One is the ZAP workbench with a highlighted context menu item on the Request-Response tab with the text "Move Tab to New Window". The other windo
Again, the text is misleading.

2024-09-19 08:22 UTC, psiinon commented on site/content/blog/2024-09-18-detachable-tabs/index.md
> +To pop out a tab into a new window, simply right click on it, and select "Move Tab to New Window".
How can they pop it back in? (I know the answer, but other people wont).
Does this work in all of the ZAP screen modes?
Are there any gotchas?

2024-09-19 08:28 UTC, psiinon commented
Yeah, that would be fine.
I still think a post to the user group might be better at this state...

2024-09-20 19:04 UTC, closed without merging