update evangelists.yaml
zaproxy/zaproxy-website pull request #375
Opened 2021-03-24 14:33 UTC by egodoy-cl

- name: Eduardo Godoy
  email: egodoy@agc.cl
  twitter: EdoGodoy
  linkedin: https://www.linkedin.com/in/EduardoGodoy/
  locations: Santiago, Chile
  language: Spanish, English
  has_talks: Y
  has_training: Y
  notes: Virtual CISO, Security Advisor

**- Summary**

**- Test plan**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

2021-03-24 14:35 UTC, kingthorin commented
To address the DCO requirement you'll need to sign-off the commit(s):

- https://github.com/zaproxy/zaproxy/blob/develop/CONTRIBUTING.md#developer-certificate-of-origin
- https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff

2021-03-24 20:33 UTC, kingthorin requested changes

2021-03-24 20:33 UTC, kingthorin commented on site/data/evangelists.yaml
```suggestion

```

It would be nice if there was just one blank between, as with the others.

2021-03-25 15:08 UTC, thc202 commented
This now has conflicts.

2021-06-15 16:28 UTC, thc202 commented
@egodoy-cl do you agree with DCO? We can address the remaining tasks.

2021-08-18 18:26 UTC, kingthorin commented
@egodoy-cl do you plan to address the earlier comments/questions, and now conflicts?

2021-09-22 00:29 UTC, kingthorin commented
Closing. It’s been over a month.

2021-09-22 00:29 UTC, closed without merging